# Generated by Django 3.2.5 on 2021-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
