# Generated by Django 3.2.5 on 2021-07-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bloguser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='username',
            new_name='fullname',
        ),
    ]
