# Generated by Django 3.2.5 on 2021-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_bloguser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(null=True, upload_to='images/posts'),
        ),
    ]
