# Generated by Django 3.2.5 on 2021-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
