# Generated by Django 3.2.5 on 2021-07-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bloguser'),
            preserve_default=False,
        ),
    ]
