# Generated by Django 3.2.5 on 2021-07-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('UPVOTE', 'upvote'), ('DOWNVOTE', 'downvote')], max_length=8),
        ),
    ]
