# Generated by Django 3.2.5 on 2021-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_vote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='images/profiles'),
        ),
        migrations.DeleteModel(
            name='BookMark',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
