# Generated by Django 3.2.5 on 2021-08-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210730_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
